name: "Terraform plan_action"
on:
    push:
        branches: 
            - 'main'
    pull_request:
        branches:
            - 'main'
concurrency:
    group: ${{ github.head_ref || github.ref }}

permissions:
    id-token: write
    contents: read
    pull-requests: write

env:
    TF_LOG: INFO
    AWS_REGION: ${{ vars.AWS_REGION }}
    AWS_ROLE: ${{ secrets.AWS_ROLE }}
    ROLE_SESSION: Github-OIDC-TERRAFORM

jobs:
    development-plan:
        concurrency:
            group: ${{ github.base_ref }}-development_environment
            cancel-in-progress: false
        runs-on: ubuntu-latest
        environment: development
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: development-plan
              uses: Cloud-Engineering-EA/composite-action-terraform-deploy@v1.0
              with:
                terraform_action: plan
                environment: development






